version: "3.8"

services:
  paperless-rest:
    build:
      context: ./apps/paperless-rest
      dockerfile: Dockerfile
    image: paperless-rest
    ports:
    - 8080:8080
    container_name: paperless-rest
  paperless-ui:
    build:
      context: ./apps/paperless-ui
      dockerfile: Dockerfile
    image: paperless-ui
    ports:
      - 4200:80
    container_name: paperless-ui
