version: "3.8"

services:
  paperless-rest:
    build:
      context: ./apps/paperless-rest
      dockerfile: Dockerfile
    image: paperless-rest
    ports:
    - 8080:8080
    container_name: paperless-rest
  paperless-ui:
    build:
      context: ./apps/paperless-ui
      dockerfile: Dockerfile
    image: paperless-ui
    ports:
      - 4200:80
    configs:
      - source: nginx-config
        target: /etc/nginx/nginx.conf
    container_name: paperless-ui
  paperless-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=paperless
      - POSTGRES_PASSWORD=paperless
      - POSTGRES_DB=paperless
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    container_name: paperless-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U paperless" ]
      interval: 10s
      timeout: 5s
      retries: 5
  paperless-queue:
    image: rabbitmq:management
    container_name: paperless-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=paperless
      - RABBITMQ_DEFAULT_PASS=paperless
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  paperless-minio:
    image: docker.io/bitnami/minio:2022
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=paperless
      - MINIO_ROOT_PASSWORD=paperless
      - MINIO_DEFAULT_BUCKETS=documents
    container_name: paperless-minio
  paperless-ocr:
    build:
      context: ./apps/paperless-ocr
      dockerfile: Dockerfile
    image: paperless-ocr
    ports:
      - 8082:8082
    environment:
      - TESSDATA_PREFIX=/usr/share/tesseract-ocr/4.00/tessdata
    container_name: paperless-ocr

  paperless-elastic:
    image: elasticsearch:8.7.1
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
      - "xpack.security.enrollment.enabled=false"
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    ports:
      - 9200:9200
      - 9300:9300
  paperless-kibanba:
    image: docker.elastic.co/kibana/kibana:8.2.3
    ports:
      - 5601:5601

configs:
  nginx-config:
    file: nginx/nginx.conf

volumes:
  db:
  minio_data:
    driver: local
