version: "3.8"

services:
  paperless-rest:
    build:
      context: ./apps/paperless-rest
      dockerfile: Dockerfile
    image: paperless-rest
    ports:
    - 8087:8087
    container_name: paperless-rest
  paperless-ui:
    build:
      context: ./apps/paperless-ui
      dockerfile: Dockerfile
    image: paperless-ui
    ports:
      - 4200:80
    configs:
      - source: nginx-config
        target: /etc/nginx/nginx.conf
    container_name: paperless-ui
  paperless-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    container_name: paperless-db

configs:
  nginx-config:
    file: nginx/nginx.conf

volumes:
  db:
    driver: local
